sudo: required

language: ruby

env:
  global:
    - USER=yokogawa
    - REPO=debian
    - SUITE=lenny

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y debootstrap

script:
  - make IMAGE=${USER}/${REPO} SUITE=${SUITE}

# https://docs.travis-ci.com/user/docker/
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ${USER}/${REPO}:${SUITE};
    fi
