sudo: required

language: ruby

env:
  global:
    - USER=yokogawa
    - REPO=debian
    - SUITE=lenny

services:
  - docker

script:
  - make IMAGE=${USER}/${REPO} SUITE=${SUITE}

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ${USER}/${REPO}:${SUITE};
    fi
